apiVersion: v1
kind: ConfigMap
metadata:
  name: digit-ui-tl
  namespace: egov
data:
  sub_filter.conf: |
    # Apply only on HTML responses (do NOT touch JS)
    sub_filter_once off;
    sub_filter_types text/html;

    # Load TL-specific global config (CONTEXT_PATH = "digit-ui-tl")
    sub_filter '</head>' ' <script src="https://pgr-eks-cluster-assets-bucket.s3.ap-south-1.amazonaws.com/digit-ui-tl/globalConfigsTL.js" type="text/javascript"></script></head>';
