# Replace with the name which you want to give to your EKS cluster
# Cluster name can have only lowercase alphanumeric characters and hyphens
# For example: "digit-demo"
cluster_name: "pgr-eks-cluster"

# Name you want to give to your Database
# DB name must contain only alphanumeric characters
db_name: "egovpgrdb"

# Replace with DB username you want
# DB user name must contain only alphanumeric characters
db_username: "egovpgr"

# Replace with Domain name you want for your web applications
domain_name: "www.pgrdigit.com"

# Replace with the name you want to give to your S3 bucket which is used to store the terraform state
terraform_state_bucket_name: "pgrdigit-s3-bucket"

public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpUlIyjVpIhzkWpZfEyaHMguym0JvCNTIsxpDQR+z31wQ2hfZINC3s9aUS+SPCRpk3b2FYbuJ+FbeyrlwtqIJKWae0V9hMI04PV/hhOtetmukclcE2PnuIBUmvkAexfFx+uFzaNfmYuZPJnNJo0IB9vlXUiofICmd9SOWfr4K9PX/ntc5eMTso4mgDDAsJbNHjC7sLZaO+Kye2fiqYnSdK8caQ/mp3vG+PuXIsrCrj7vW+noDctTPNjYcxEosUH5jwVNAGnenN4/ANHD55vO13fLUrP+e2YIDt7k4CwGCDWQNV6c4pl4MyncWNTFd+IbWu5ROAzYm2Znei1pXfjYU1"

tenant_id: "statea"
