apiVersion: v2
name: tl-calculator
description: DIGIT Trade License Calculator service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: 0.0.5
    repository: file://../../common
