# Common Labels
labels:
  app: "tl-calculator"
  group: "tl"

# Ingress Configs – DISABLED (internal service only)
ingress:
  enabled: false
  zuul: false
  context: "tl-calculator"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: false   # first time true then false
    schemaTable: "tl_calculator_schema"
    image:
      repository: "egovio/tl-calculator-db"
      tag: "1648-5aebb2e"
      pullPolicy: "IfNotPresent"
    env: |
      - name: "DB_URL"
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: db-url
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}
      - name: "FLYWAY_USER"
        valueFrom:
          secretKeyRef:
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: flyway-locations

# Container Configs
image:
  repository: "egovio/tl-calculator"
  tag: "1648-5aebb2e"

replicas: "1"

healthChecks:
  enabled: true
  livenessProbePath: "/tl-calculator/health"
  readinessProbePath: "/tl-calculator/health"

appType: "java-spring"
tracing-enabled: true

heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
java-enable-debug: "false"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXTPATH
    value: "/tl-calculator"

  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url

  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "tl-calculator"
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer

  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2

  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service

  - name: EGOV_TL_SERVICES_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: tl-services

  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}

  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}

  - name: SERVER_PORT
    value: "8080"

  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  - name: TRACER_REQUESTLOGGINGENABLED
    value: "true"
  {{- end }}

memory_limits: 384Mi
